name: CI

on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - main

permissions:
  contents: read

env:
  DOTNET_VERSION: "10.x"

jobs:
  build-test:
    name: Build, Test and Coverage
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Cache NuGet packages
        uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj', '**/*.props', '**/*.targets', '**/global.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Restore
        run: dotnet restore FinanceFlow.slnx

      - name: Build
        run: dotnet build FinanceFlow.slnx --configuration Release --no-restore

      - name: Test with Coverage
        run: >
          dotnet test FinanceFlow.slnx
          --configuration Release
          --no-build
          --no-restore
          --collect:"XPlat Code Coverage"
          --results-directory ./TestResults

      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: antoniomrrds/finance_flow
